version: '3'

services:
  web:
    container_name: web_switch
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes: 
      - .:/code/
    ports: 
      - "3000:3000"
      - "8000:8000"
  
  db:
    container_name: db_switch
    restart: always
    image: postgres:13
    ports: 
      - "5432:5432"
    env_file:
      - ./.env

networks:
  default:
    external:
      name: shared

