version: '3'

services:
  web:
    container_name: switch_web
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes: 
      - .:/code/
    ports: 
      - "5050:3000"
      - "5051:8000"
  
  db:
    container_name: switch_db
    restart: always
    image: postgres:13
    ports: 
      - "5052:5432"
    env_file:
      - ./.env

networks:
  default:
    name: shared

