# Generated by Django 3.2 on 2021-04-22 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('external_id', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('power', models.BooleanField(default=False)),
            ],
        ),
    ]
